words = [
  { word = "unobtrusive", def = "(adj) Not in the way, forgettable" },
  { word = "sniggers", def = "(n) Laughter, derisive" },
  { word = "jettison", def = "(v) Get rid of" },
  { word = "crouched", def = "(v) to bend down low" },
  { word = "flank", def = "(n) side of an object" },
  { word = "petrified", def = "(adj) hardened, preserved" },
  { word = "omens", def = "(n) signs of future events" },
  { word = "armaments", def = "(n) military weapons, gear" },
  { word = "template", def = "(?) Definition" },
]
