## https://github.com/marp-team/marp-cli#configuration-file
bespoke:
    osc: false
    transition: true
author: "Max Bruges"
themeSet: "static/rab.css"
description: "An online lesson, made by MB 🐈‍⬛"
keywords: "learn, english, literature, bruges"
lang: "en"
html: true
paginate: true
options:
    emoji:
        shortcode: true
        unicode: false
