name: Sync Marp Lessons Site

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_marp_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync HTML files
        run: |
            mkdir -p static/lessons
            rsync -avz --delete -e "ssh -p5222 -o StrictHostKeyChecking=no"   max@46.38.243.226:/home/max/marp_live/ static/lessons/
            ls -R static/lessons/

      - name: Commit lesson files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add static/lessons
          git commit -m "Sync Marp files from remote server" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
