name: Sync Marp Lessons Site

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync HTML files
        run: |
            rsync -avz --delete -e "ssh -p5222 -o StrictHostKeyChecking=no"   max@46.38.243.226:/home/max/marp_live/ static/lessons/
