name: Minify CSS

on:
  push:
    branches:
      - main
    paths:
      - "**/*.css"
  workflow_dispatch:
jobs:
  minify_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Minify CSS files
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY_PURGE: ${{ secrets.CF_API_KEY_PURGE }}
        run: |
          which bash
          bash .github/scripts/minify.sh

      - name: Commit minified CSS files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -a -m "Minified CSS" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Purge Cloudflare Cache
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H 'Content-Type: application/json' \
            -H "X-Auth-Email: ${{ secrets.CF_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CF_API_KEY_PURGE }}" \
            -d '{
              "purge_everything": true
            }')

          if [ "$response" -eq 200 ]; then
            echo "Succeeded in purge!"
          else
            echo "Purge failed with response code: $response"
            exit 1
          fi
