name: Minify CSS

on:
  push:
    branches:
      - main
    paths:
      - '**/*.css'
  workflow_dispatch:
jobs:
  minify_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Minify CSS files
        run: |
          bash .github/scripts/minify.sh

      - name: Commit minified CSS files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -a -m "Minified CSS" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
